M48
; DRILL file {KiCad 9.0.0} date 2025-06-24T17:18:06-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-24T17:18:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X119.46Y-44.565
X125.24Y-44.565
T2
X109.49Y-41.449
X109.49Y-43.481
X114.57Y-42.465
T3
X160.93Y-50.67
X169.9Y-50.67
M30
